version: '3.8'

services:
  frontend:
    build: ./welto-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./welto-frontend:/app
    depends_on:
      - backend

  backend:
    build: ./welto-backend
    ports:
      - "5000:5000"
    volumes:
      - ./welto-backend:/app
    env_file:
      - ./welto-backend/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
